# Generated by Django 4.0.2 on 2022-02-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondity', '0002_alter_category_parent_alter_category_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
