# Generated by Django 4.0.2 on 2022-02-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='img1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='status',
            field=models.IntegerField(choices=[(0, '未激活'), (1, '正常'), (2, '注销')], default=0, verbose_name='状态'),
        ),
    ]
